Anirban-Biswas-Dev/noteroom

public/js/user-profile.js, server/routers/user.js, server/schemas/students.js, server/server.js, views/bar-loader.ejs, views/login.ejs, views/user-profile.ejs
Though I have added the backend variables, I just commented them out and while working with frontend designing, keep them commented for preventing errors
=> The backend side of user-profile view

public/js/404-page.js, public/js/user-profile.js, server/errorhandlers/errors.js, server/routers/user.js, server/server.js, views/404-error.ejs
Though added error handling, their logic is commented because I haven't publish the database in the internet and for error-freeness I am not letting anyone to access the ejs variables
=> Added error handling

public/js/user-profile.js, views/user-profile.ejs
You can see that I have removed the featured notes message from javascript and implemented through ejs instead
=> Slight change in showing featured_notes ammount message

public/css/note-view.css, public/css/user-profile.css, views/note-view.ejs, views/user-profile.ejs
There are three core changes in this branch, which are, first of all, I added a template comment section. Remember, this will be changed with time and time. Second is, I ensured that the note cards work like. if anyone clicks on them, they can easily go to the notes specific page, rather than clicking on the title. The third change is minor yet kind of user friendly, which is when someone doesn't have a node on his or her profile, there will be an svd emoji plus a message. It has some issue with positioning, but can be solved later on with the back end developers input.
=> Design updates note view 

public/css/support.css
Adding this due to some unknown conflict issues
=> Client side frontend features

server/routers/note-view.js, server/routers/upload-note.js, server/routers/user.js, views/dashboard.ejs, views/note-view.ejs, views/side-panel.ejs, views/upload-note.ejs, views/user-profile.ejs
I guess, make main-pages.css the shared css files for left,right panels and search-bar
=> unhandled design in shared side panels

server/routers/note-view.js, server/routers/upload-note.js, server/routers/user.js, views/dashboard.ejs, views/note-view.ejs, views/side-panel.ejs, views/upload-note.ejs, views/user-profile.ejs
Though you merged, I don't see them on the main. So pulling again.
=> Shared side panels pull by Anirban

public/js/controller.js, public/js/dashboard.js, server/routers/note-view.js, server/server.js, views/dashboard.ejs, views/note-view.ejs, views/shared.ejs, views/side-panel.ejs
* download notes just via note-id
* share-notes on fb, wp v1.0 (note-view)
* share on wp,fb - dashboard, note-view, latest
---------
=> Latest (#82)

public/js/controller.js, server/server.js, views/side-panel.ejs, views/upload-note.ejs
From backend, this is the **FIRST** approach to search notes.
=> notes can be searched now: backend done v1.0

public/js/controller.js, public/js/dashboard.js, public/js/upload-note.js, server/errorhandlers/errors.js, server/routers/sign-up.js, server/routers/upload-note.js, server/schemas/notes.js, server/schemas/students.js, views/dashboard.ejs, views/note-view.ejs, views/upload-note.ejs
1. added error handling in upload note title
2. used full sha256 hash as username
3. randomized share message in whatsapp
=> some minor changes

public/css/upload-note.css, public/js/upload-note.js, views/upload-note.ejs
Now multiple images can be selected at a time in upload section. They will be upload **in the order they are selected**.
=> multiselect image with stack-num update

package-lock.json, package.json, public/js/controller.js, server/routers/dashboard.js, server/schemas/notifications.js, views/side-panel.ejs
Anirban check the changes for this commit to get a good overview
=> notif. status added in frontend and setup the logic in backend to change the status to true

public/js/controller.js, public/js/dashboard.js
* isRead field needs to be auto, now it is always true. 
* manageSavedNotes and manageNotis need to be encapsulated to one class
=> indexedDb for notis instead of localStorage

public/js/note-view.js, server/routers/controller.js, server/routers/dashboard.js, server/routers/note-view.js, server/routers/user.js, server/schemas/notifications.js, server/server.js, views/note-view.ejs, views/side-panel.ejs
=> Added a new type schema in noti='mention'
=> No socket has used in sending mention notification. They will be showed after refreshing.
=> Mention dropdown added with Tribute.JS.

public/js/controller.js, public/js/note-view.js, server/helpers/utils.ts, server/routers/note-view.ts, views/note-view.ejs
Automated mention add in reply box and showing `@displayname` in reply and feedbacks
=> More user-friendly thread-section

package-lock.json, package.json, public/js/controller.js, public/js/dashboard.js, server/helpers/emailTemplates.ts, server/helpers/utils.ts, server/routers/note-view.ts, server/routers/reset-password.ts, server/schemas/password_reset_tokens.ts, server/server.ts, server/services/apis.ts, server/services/emailService.ts, server/services/noteService.ts, server/services/resetTokenService.ts, server/services/userService.ts, views/dashboard/components/note-menu.ejs, views/dashboard/dashboard.ejs, views/note-view/note-view.ejs, views/reset-password.ejs
Frontend tasks:
1. design the forms
2. design the emails
=> Password reset done from backend

public/css/note-view.css, public/js/note-view.js, views/note-view/components/comment-box.ejs, views/note-view/components/note-engagements.ejs, views/note-view/note-view.ejs
Updated only note-view by not changing dashboard functionality(updates later)
=> Update SVG sizes and simplify note engagements component

frontend/src/public/css/upload-note.css
=> update upload-note.css to increase border-radius for improved aesthetics

frontend/src/pages/upload-note/UploadNote.tsx, frontend/src/public/css/upload-note.css
designed the carousel as given in figma
=> refactor: update styles for upload note component

frontend/src/pages/upload-note/ImageContainer.tsx, frontend/src/public/css/upload-note.css
fixed the overflowing issue of the upload-container
=> fixed issue

backend/package.json, backend/services/apis/auth.ts, backend/swaggers/authSwagger.ts, frontend/src/pages/login/Login.tsx, frontend/src/pages/sign-up/SignUp.tsx, frontend/src/partials/GoogleLogin.tsx, package-lock.json
changed the GOOGLE_CLIENT_ID from .env file and added google login/signup in auth.ts file and installed a package and added swagger for google auth
=> google login/signup

backend/services/apis/upload.ts, backend/services/services/userService.ts, backend/swaggers/uploadSwagger.ts
1. Implemented the business logic for change profile details
2. Added API Documentation using Swagger for Link and Files API.
=> Updated profile.ts and swagger

backend/server.ts, backend/services/apis/mcq.ts, backend/services/apis/profile.ts, backend/swaggers/mcqSwagger.ts, backend/swaggers/profileSwagger.ts
1. Added MCQ Response API development
2. Added swagger for profile change and mcq vote
3. Added the logger in /api/users/change
=> Added mcq.ts

frontend/package.json, frontend/src/pages/upload-note/DraftPost.tsx, frontend/src/pages/upload-note/UploadNote.tsx, frontend/src/pages/upload-note/YoutubeLinkContainer.tsx, frontend/src/pages/upload-note/dexieDB.ts, frontend/src/public/css/upload-note.css, package-lock.json
All the css in youtube link container is in inline.
=> Redesigned youtube link container, added drafts management

backend/__tests__/friends.test.ts, backend/apis/friends.api.ts, backend/services/friends.service.ts
1. Changed the friend-follow flow in a way that when someone sends friend request, if that is declined, that will be converted to a follower of the declined user. Otherwise they will be considered as friends.
=> frnd-flw:rule:Changed the friend-follow

backend/__tests__/friends.test.ts
1. used in-memory mongodb database which I used before
=> jest:test:modified friend service tests

backend/schemas/users.model.ts
1. added Social links field in the students document.
=> usr-prfl:feat:Social links field in the students document.
